Features
PatrykPut/Uebungsprojekt pull request #7
Opened 2023-09-19 13:30 UTC by PatrykPut

Seite für detailinformationen über die Spiele erstellt und Refactoring.

2023-09-20 04:08 UTC, n00bi14 requested changes

2023-09-20 04:08 UTC, n00bi14 commented on Frontend/src/UserInterface/Games/CardDeck.tsx
> +        let json = [...originalJson]
`let` solltest du nicht benötigen. Versuche JavaScript immer funktional zu schreiben und `const` zu verwenden.

2023-09-20 04:08 UTC, n00bi14 commented on Backend/Java/demo/src/main/java/Projekt/domain/Game.java
> +    public String getTrailer() {
In deine Domänenklasse gehören keine Annotationen für die Datenbank oder den Jackson-Parser.
Hier musst du noch ein Datenbank-Entity und ein DTO erstellen.

2023-09-20 07:20 UTC, PatrykPut commented on Backend/Java/demo/src/main/java/Projekt/domain/Game.java
> +    public String getTrailer() {
Ok dann ändere ich das noch

2023-09-21 09:37 UTC, n00bi14 reviewed
Nachdem due die Ordner verschoben hast kannst du dir folgendes mal angucken:

- Service Layer einführen. Welchen Zweck hat der und was schreibt man alles in einen Service?

- Wie kannst du die Null-Checks in den Mappern entfernen? Null-Checks sind immer eine Fehlerquelle, weshalb wir die eigentlich nicht so oft schreiben und sehen wollen.

2023-09-21 09:37 UTC, n00bi14 commented on Backend/Java/demo/src/main/java/Projekt/dto/GameDto.java
> +    public Long getId() {
DTOs neben oder unter den Controller legen. Es gibt kein eigenes Layer für "dto"

2023-09-21 09:37 UTC, n00bi14 commented on Backend/Java/demo/src/main/java/Projekt/entities/GameEntity.java
> +    private Long id;
Ähnlich wie bei den DTOs. Die Entities gehören in den Repository Layer

2023-09-21 09:37 UTC, n00bi14 commented on Backend/Java/demo/src/main/java/Projekt/services/GameRepository.java
> +public interface GameRepository extends JpaRepository<GameEntity, Long> {            //erweitert das generische CRUD Repository
Der Ordner heißt "Service". Das hier ist ein Repository.

2023-09-22 08:13 UTC, merged