Features
PatrykPut/Uebungsprojekt pull request #9
Opened 2023-09-25 14:26 UTC by PatrykPut

Tests geschrieben und im Frontend ein wenig refactoring

2023-09-25 14:27 UTC, PatrykPut commented
Ich weiß wieder nicht warum die alten commits miteinbezogen wurden aber eigentlich geht es nur um den letzten.

2023-09-26 04:35 UTC, n00bi14 requested changes

2023-09-26 04:35 UTC, n00bi14 commented on Backend/Java/demo/src/test/java/Projekt/service/AllGamesTest.java
> +    public void getAllGamesTest() {
Die Methoden sollten sol benannt werden, dass daraus zu erkennen ist, wie die Fachlichkeit ist und was du hier genau getestet hast. 
Nur dadurch können Tests auch als Dokumentation verwendet werden.

2023-09-26 04:35 UTC, n00bi14 commented on Backend/Java/demo/src/main/java/Projekt/service/GamesById.java
> +    @Service
Die Filter sind kein Services

2023-09-26 04:35 UTC, n00bi14 commented on Backend/Java/demo/src/test/java/Projekt/service/GamesByIdTest.java
> +    public void getGameWithRatingsTest() {
Du hast quasi alles gemockt und nur leere Objekte verwendet. Man kann nicht erkennen, was hier getestet werden soll

2023-09-26 04:35 UTC, n00bi14 commented on Backend/Java/demo/src/test/java/Projekt/service/GamesFilteredByStarsTest.java
> +class GamesFilteredByStarsTest {
Leere Klasse...

2023-09-26 07:49 UTC, PatrykPut commented on Backend/Java/demo/src/test/java/Projekt/service/GamesFilteredByStarsTest.java
> +class GamesFilteredByStarsTest {
Die war ich gerade am bearbeiten. Ups...

2023-09-26 09:22 UTC, merged